#! /bin/bash
# sh -> bash for debian. By J. R. Peterson. 2015/Jun.

pushd "`dirname "$0"`" > /dev/null 2>&1; rootdir="$PWD"; popd > /dev/null 2>&1;

"$rootdir/usearchdir/bin/usearch" "$@"
# input file name can have space
